# Set base URL for site - should end with a trailing slash
baseUrl = "https://fun-with-blog.firebaseapp.com/"

theme = "slick"

# Site title (not shown if commented out or set to false)
# (If you disable this, add some link on the index page inside menu.main,
#  otherwise your visitors will get confused and lost...)
title = "Fun with Flutter"

languageCode = "en"
defaultContentLanguage = "en-us"

# Will appear below the footer links with a © sign and the current year
copyright = "Fun with Flutter — All rights reserved."


pygmentsCodefences = true               # Enable highlighting inside codefences
pygmentsCodeFencesGuessSyntax = true    # Highlight code without language tag
pygmentsUseClasses = true               # Use external style sheet
pygmentsUseClassic = false              # Force use of chroma

canonifyURLs = true
preserveTaxonomyNames = true

# Configure pagination
paginate = 10
paginatePath = "page"

[params]
    # Site subtitle (not shown if commented out or set to false)
    subtitle = "Blog"

    # Site description
    description = "Companion Blog for the Fun with Flutter YouTube channel"

    # Favicon file (relative to baseURL - place below static folder)
    favicon = "favicon.png"
    # Custom css file (relative to baseURL - place below static folder)
    css = "custom.css"

    # Define formatting of dates
    # (optional, falls back to RFC822 format if not set)
    # For reference to date and time formatting, see:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    # Make sure to set showMetaDates to true to see any dates
    dateFmt = "Mon, 02 Jan 2006 15:04:05 MST"

    # Customize the text of the 404 page here
    errorPageText = "There's nothing to see here, please move along!"

    # Header with title/subtitle can be disabled here.
    # (If you disable this, add some link on the index page inside menu.main,
    #  otherwise your visitors will get confused and lost...)
    showNavHeader = true

    # Decide if only summaries are shown on the main page or the full content
    showFullContent = true

    # If false no pagination is shown when there is nothing to paginate
    showEmptyPagination = true

    # If false the dates for the posts are not shown
    showMetaDates = true

    # If false the taxonomy links for the posts are not shown
    showMetaLinks = true

    # Uses Hugo internal templates if set
    opengraph = false
    schema = false
    twitter_cards = false


# Define all supported taxonomies (add series to the default)
[taxonomies]
    tag = "tags"
    thumbnail = "thumbnails"
    description = "descriptions"
    # categories = "categories"
    # series = "series"


[author]
    name = "Gordon Hayes"
    email = "funwithflutter@gmail.com"


[menu]

    # Configure main menu entries (header)
    # Currently set to list all taxonomies and posts
    [[menu.main]]
        identifier = "post"
        name = "Posts"
        title = "All posts"
        url = "/posts/"
        weight = 1

    #[[menu.main]]
    #    identifier = "categories"
    #    name = "Categories"
    #    title = "All categories"
    #    url = "/categories/"
    #    weight = 2

    [[menu.main]]
        identifier = "tags"
        name = "Tags"
        title = "All tags"
        url = "/tags/"
        weight = 2

    #[[menu.main]]
    #    identifier = "series"
    #    name = "Series"
    #    title = "All series"
    #    url = "/series/"
    #    weight = 2


    # Define the entries for post metadata
    # Identifiers should match with the taxonomy entries
    #[[menu.meta]]
    #    identifier = "categories"
    #    name = "Categories"
    #    weight = 1
    #[[menu.meta]]
    #    identifier = "series"
    #    name = "Series"
    #    weight = 2
    [[menu.meta]]
        identifier = "tags"
        name = "Tags"
        weight = 3


    # Add some footer links to your likings
    [[menu.footer]]
        name = "GitHub"
        title = "Fun with Github repository"
        url = "https://github.com/funwithflutter/"
        weight = 1

    [[menu.footer]]
        name = "YouTube"
        title = "Fun with Flutter YouTube"
        url = "https://www.youtube.com/funwithflutter"
        weight = 2

[outputs]
  home = ["json","html"]
  page = ["html"]
  section = ["html"]